spring:
  profiles:
    active: native
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations:
            file:///D/:/project/java/microservice/microservices/ms-config-properties/{application}/{profile},
            file:///D/:/project/java/microservice/microservices/ms-config-properties/global/{profile}
---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/isilona/microservices/
          search-paths:
            - "ms-config-properties/{application}/{profile}"
            - "ms-config-properties/global/{profile}"

